site_name: Telemetry Forge Product Documentation
site_url: https://telemetryforge.io
nav:
  - Home: index.md
  - Telemetry Forge Agent:
    - agent/index.md
    - Features:
      - Overview: agent/features/index.md
      - Record Deduplication: agent/features/record-deduplication.md
      - Log Sampling: agent/features/log-sampling.md
      - Git Configuration Auto-Reload: agent/features/git-config-auto-reload.md
      - Hardening and Optimisation: agent/build-optimisations.md
      - AI filtering and routing: agent/features/llm-tagging.md
    - Security:
      - Overview: agent/security.md
      - CVE Information: agent/security/cves.md
      - Current Triaged Vulnerabilities: agent/security/triaged.md
    - Supported Platforms: agent/supported-platforms.md
    - Version Mapping: agent/version-mapping.md
  - Fully Managed Logs:
    - fully-managed-logs/index.md
  - Fleet Manager:
    - fleet-manager/index.md
plugins:
  - privacy
  - offline
  - search
  - social
  - meta
  - redirects:
      redirect_maps:
        "security.md": "agent/security.md"
        "build-optimisations.md": "agent/build-optimisations.md"
        "supported-platforms.md": "agent/supported-platforms.md"
        "version-mapping.md": "agent/version-mapping.md"
        "features/git-config-auto-reload.md": "agent/features/git-config-auto-reload.md"
        "features/log-sampling.md": "agent/features/log-sampling.md"
        "features/record-deduplication.md": "agent/features/record-deduplication.md"
        "security/cves.md": "agent/security/cves.md"
        "security/triaged.md": "agent/security/triaged.md"
markdown_extensions:
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - toc

theme:
  name: material
  highlightjs: true
  copyright: Telemetry Forge 2026
  custom_dir: overrides

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: teal
      accent: teal

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: teal
      accent: teal
  features:
    - header.autohide
    - announce.dismiss
    - navigation.top
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
extra:
  homepage: https://telemetryforge.io
  # Disable made by mkdocs
  generator: false
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
      - reject
    cookies:
      analytics:
        name: Google Analytics
        checked: false
      github:
        name: Github
        checked: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/telemetryforge
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/telemetry-forge
    - icon: fontawesome/solid/paper-plane
      link: mailto:info@telemetryforge.io
copyright: >
  Copyright &copy; 2025 - 2026 Telemetry Forge
  <a href="#__consent">Change cookie settings</a>

validation:
  omitted_files: warn
  absolute_links: warn  # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: warn
  anchors: warn  # New in MkDocs 1.6