name: Build an offline version of the documentation
on:
  workflow_dispatch:

jobs:
  build:
    name: Generate documentation and upload
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - run: scripts/generate-offline.sh
        shell: bash

      - name: Debug
        if: always()
        continue-on-error: true
        run: ls -lR
        shell: bash

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: agent-documentation
          path: "*.tgz"
          if-no-files-found: error
