name: Lint PRs
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - labeled
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shellcheck-pr:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: write  # for reviewdog/action-shellcheck to report issues using PR comments
    runs-on: ubuntu-latest
    name: PR - Shellcheck
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: reviewdog/action-shellcheck@4c07458293ac342d477251099501a718ae5ef86e # v1.32.0
        with:
          reporter: github-pr-review
          fail_level: error
          pattern: |
            *.bash
            *.sh
          exclude: |
            */.git/*
            ./source/*

  actionlint-pr:
    runs-on: ubuntu-latest
    name: PR - Actionlint
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color -shellcheck=
        shell: bash

  check-orphaned-docs:
    runs-on: ubuntu-latest
    name: PR - Check Orphaned Documentation
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Check for orphaned markdown files
        run: bash ./scripts/check-orphaned-docs.sh
        shell: bash

  actions-pin-sha:
    runs-on: ubuntu-latest
    name: PR - Actions Pin SHA
    permissions:
      contents: read
      # For ReviewDog to post comments to the PR
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: suzuki-shunsuke/pinact-action@896d595f299e71d65b9d28349d6956abe144390a  # v3.0.0
        with:
          skip_push: "true"
          review: "true"
